- name: copyplaybook
  hosts: all
  tasks:
    - name: copy_file
      copy:
        src: /root/ansibleshell.sh
        dest: /root/
    - name: Shell_exe
      shell: sh /root/ansibleshell.sh
      register: target_sh
    - debug:
        var: target_sh.stdout_lines
