- name: Installing_jenkins
  hosts: all
  become: yes
  tasks:
  - name: Copying_jenkisscripts
    copy:
      src: jenconnect.sh
      dest: /home/ubuntu
  - name: shell_jenkinscript
    shell: sh /home/ubuntu/jenconnect.sh
